# Generated by Django 5.2.12 on 2026-03-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('check_type', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], default='pull', max_length=10)),
                ('is_public', models.BooleanField(default=True)),
                ('last_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('heartbeat_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
