# Generated by Django 5.2.12 on 2026-04-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
